#!/usr/bin/env bun
/**
 * Build OpenCode for Android (aarch64)
 *
 * This script:
 * 1. Generates the models-snapshot.js
 * 2. Loads migrations
 * 3. Bundles OpenCode using Bun.build() with compile targeting the host platform
 * 4. Extracts the module graph from the compiled binary
 * 5. Appends it to our Android bun binary to create the final standalone
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"

// These are set by the build-opencode.sh wrapper script
const OPENCODE_DIR = process.env.OPENCODE_DIR || (() => { throw new Error("OPENCODE_DIR env var not set") })()
const ANDROID_BUN = process.env.ANDROID_BUN || (() => { throw new Error("ANDROID_BUN env var not set") })()
const OUTPUT_DIR = process.env.OUTPUT_DIR || (() => { throw new Error("OUTPUT_DIR env var not set") })()

// Validate Android bun exists
if (!fs.existsSync(ANDROID_BUN)) {
  console.error("Android bun binary not found at:", ANDROID_BUN)
  process.exit(1)
}

process.chdir(OPENCODE_DIR)

const VERSION = process.env.OPENCODE_VERSION || "1.3.13"
const CHANNEL = process.env.OPENCODE_CHANNEL || "latest"

console.log(`Building OpenCode v${VERSION} (channel: ${CHANNEL}) for Android aarch64`)

// Step 1: Generate models-snapshot.js
console.log("\n=== Step 1: Generating models-snapshot.js ===")
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
let modelsData: string
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else {
  console.log(`Fetching from ${modelsUrl}/api.json ...`)
  modelsData = await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
}
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// Step 2: Load migrations
console.log("\n=== Step 2: Loading migrations ===")
const migrationDirs = (
  await fs.promises.readdir(path.join(OPENCODE_DIR, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(OPENCODE_DIR, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// Step 3: Build with Bun.build() --compile for the HOST platform
// This creates a standalone binary for the host, from which we extract the module graph
console.log("\n=== Step 3: Bundling OpenCode ===")

const plugin = createSolidTransformPlugin()

// Find parser.worker.js
const localPath = path.resolve(OPENCODE_DIR, "node_modules/@opentui/core/parser.worker.js")
const rootPath = path.resolve(OPENCODE_DIR, "../../node_modules/@opentui/core/parser.worker.js")
let parserWorkerResolved: string
try {
  parserWorkerResolved = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
} catch {
  // Try bun's module resolution
  parserWorkerResolved = require.resolve("@opentui/core/parser.worker.js")
}
console.log(`Parser worker: ${parserWorkerResolved}`)

const workerPath = "./src/cli/cmd/tui/worker.ts"

const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(OPENCODE_DIR, parserWorkerResolved).replaceAll("\\", "/")

await $`rm -rf ${OUTPUT_DIR}`
await $`mkdir -p ${OUTPUT_DIR}`

// Build with --compile for the HOST platform to get a standalone binary
// We'll extract the module graph from it
const hostBinaryPath = path.join(OUTPUT_DIR, "opencode-host")

console.log("Building standalone binary for host platform...")
const result = await Bun.build({
  conditions: ["browser"],
  tsconfig: "./tsconfig.json",
  plugins: [plugin],
  compile: {
    autoloadBunfig: false,
    autoloadDotenv: false,
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    outfile: hostBinaryPath,
    execArgv: [`--user-agent=opencode/${VERSION}`, "--use-system-ca", "--"],
  },
  entrypoints: ["./src/index.ts", parserWorkerResolved, workerPath],
  define: {
    OPENCODE_VERSION: `'${VERSION}'`,
    OPENCODE_MIGRATIONS: JSON.stringify(migrations),
    OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
    OPENCODE_WORKER_PATH: workerPath,
    OPENCODE_CHANNEL: `'${CHANNEL}'`,
    OPENCODE_LIBC: "",
  },
})

if (!result.success) {
  console.error("Build failed:")
  for (const msg of result.logs) {
    console.error(msg)
  }
  process.exit(1)
}

console.log(`Host standalone binary: ${hostBinaryPath}`)

// Step 4: Extract module graph from host binary
console.log("\n=== Step 4: Extracting module graph ===")

const hostBinary = await Bun.file(hostBinaryPath).arrayBuffer()
const hostBytes = new Uint8Array(hostBinary)

// The standalone format for ELF:
// [bun binary] [module graph bytes] [8 bytes: total_byte_count as u64 LE]
// The module graph bytes end with the trailer "\n---- Bun! ----\n"

// Read the last 8 bytes to get total_byte_count
const totalByteCountView = new DataView(hostBinary, hostBytes.length - 8, 8)
// Read as little-endian u64 (we'll use Number since JS BigInt is needed for full u64)
const totalByteCountLow = totalByteCountView.getUint32(0, true)
const totalByteCountHigh = totalByteCountView.getUint32(4, true)
const totalByteCount = totalByteCountLow + totalByteCountHigh * 0x100000000

console.log(`Host binary size: ${hostBytes.length}`)
console.log(`Total byte count (from trailer): ${totalByteCount}`)

// total_byte_count = bun_seek_position + module_graph.length + 8
// bun_seek_position is where the module graph starts (= size of bun binary)
// So module_graph.length = total_byte_count - bun_seek_position - 8
// And bun_seek_position = hostBytes.length - module_graph.length - 8
// So: bun_seek_position = totalByteCount - module_graph.length - 8... circular

// Actually, from the code:
// seek_position = fstat.size of the bun copy (the original bun size)
// total_byte_count = seek_position + bytes.len + 8
// So: bytes.len = total_byte_count - seek_position - 8
// And the file is: [bun copy (seek_position bytes)] [module graph (bytes.len bytes)] [8 bytes total_byte_count]
// So file size = seek_position + bytes.len + 8 = total_byte_count
// Wait, that means total_byte_count == file size? Let me re-check...
// 
// From the code:
//   total_byte_count = seek_position + bytes.len + 8;
//   write(bytes)
//   write(&total_byte_count)  // 8 bytes
// So the final file size = seek_position + bytes.len + 8 = total_byte_count
// BUT wait, seek_position is the fstat.size BEFORE writing, and the file was copied from bun
// So seek_position = original bun size
// And the final file = [bun(seek_position)] [module_graph(bytes.len)] [total_byte_count(8)]
// File size = seek_position + bytes.len + 8 = total_byte_count

// So totalByteCount should equal hostBytes.length
if (totalByteCount !== hostBytes.length) {
  console.error(`ERROR: total_byte_count (${totalByteCount}) != file size (${hostBytes.length})`)
  console.error("This is unexpected. The standalone binary format may have changed.")
  process.exit(1)
}

// To find the module graph start, we need to know the host bun size
// The host bun binary is at /usr/local/bin/bun or wherever bun is installed
const hostBunPath = process.execPath
const hostBunSize = fs.statSync(hostBunPath).size
console.log(`Host bun (${hostBunPath}) size: ${hostBunSize}`)

const moduleGraphBytes = hostBytes.slice(hostBunSize, hostBytes.length - 8)
console.log(`Module graph size: ${moduleGraphBytes.length}`)

// Verify trailer
const trailerStr = "\n---- Bun! ----\n"
const trailerBytes = new TextEncoder().encode(trailerStr)
const possibleTrailer = moduleGraphBytes.slice(moduleGraphBytes.length - trailerBytes.length)
const trailerMatch = trailerBytes.every((b, i) => b === possibleTrailer[i])
console.log(`Trailer found: ${trailerMatch}`)

if (!trailerMatch) {
  // Try to find the trailer in the binary
  const trailerBuf = Buffer.from(trailerStr)
  let trailerPos = -1
  for (let i = hostBytes.length - 100; i >= hostBytes.length - 10000; i--) {
    if (hostBytes[i] === 0x0a && Buffer.compare(trailerBuf, Buffer.from(hostBytes.slice(i, i + trailerBuf.length))) === 0) {
      trailerPos = i
      break
    }
  }
  if (trailerPos >= 0) {
    console.log(`Found trailer at offset ${trailerPos}`)
    console.log(`Bun binary appears to be ${trailerPos - moduleGraphBytes.length + hostBunSize} bytes`)
  }
  console.error("WARNING: Trailer mismatch. Proceeding anyway...")
}

// Step 5: Patch the module graph for Android
console.log("\n=== Step 5: Patching module graph for Android ===")

// The module graph format (from StandaloneModuleGraph.zig):
//   [string data: all file names, contents, sourcemaps, bytecodes concatenated]
//   [CompiledModuleGraphFile array: stride=36 bytes each]
//   [Offsets struct: 32 bytes]
//   [trailer: "\n---- Bun! ----\n"]
//
// Offsets struct layout (32 bytes, little-endian):
//   byte_count:              u64  (8 bytes) - size of everything before the Offsets struct
//   modules_ptr.offset:      u32  (4 bytes)
//   modules_ptr.length:      u32  (4 bytes)
//   entry_point_id:          u32  (4 bytes)
//   compile_exec_argv.offset:u32  (4 bytes)
//   compile_exec_argv.length:u32  (4 bytes)
//   flags:                   u32  (4 bytes)
//
// CompiledModuleGraphFile layout (36 bytes):
//   name.offset:     u32 (4)
//   name.length:     u32 (4)
//   contents.offset: u32 (4)
//   contents.length: u32 (4)
//   sourcemap.offset:u32 (4)
//   sourcemap.length:u32 (4)
//   bytecode.offset: u32 (4)
//   bytecode.length: u32 (4)
//   encoding:        u8  (1)
//   loader:          u8  (1)
//   module_format:   u8  (1)
//   padding:         u8  (1)

const trailer = "\n---- Bun! ----\n"
const trailerBuf = Buffer.from(trailer)
const OFFSETS_SIZE = 32
const STRIDE = 36

// Parse the module graph
const mgBuf = Buffer.from(moduleGraphBytes)
const trailerPosInMg = mgBuf.lastIndexOf(trailerBuf)
if (trailerPosInMg < 0) throw new Error("Trailer not found in module graph!")

// Offsets struct is just before the trailer
const offsetsStart = trailerPosInMg - OFFSETS_SIZE
const byteCount = Number(mgBuf.readBigUInt64LE(offsetsStart))  // points to start of Offsets struct
const modOff = mgBuf.readUInt32LE(offsetsStart + 8)
const modLen = mgBuf.readUInt32LE(offsetsStart + 12)
const entryId = mgBuf.readUInt32LE(offsetsStart + 16)
const argvOff = mgBuf.readUInt32LE(offsetsStart + 20)
const argvLen = mgBuf.readUInt32LE(offsetsStart + 24)
const flags = mgBuf.readUInt32LE(offsetsStart + 28)

console.log(`Module graph: trailer at ${trailerPosInMg}, offsets at ${offsetsStart}`)
console.log(`byte_count=${byteCount}, modules_ptr=(${modOff},${modLen}), entry_id=${entryId}`)

const nModules = modLen / STRIDE
console.log(`Number of modules: ${nModules}`)

// Parse all module entries
interface ModEntry {
  nameOff: number; nameLen: number
  contOff: number; contLen: number
  smOff: number; smLen: number
  bcOff: number; bcLen: number
  encoding: number; loader: number; moduleFormat: number; padding: number
  name: string
}

const modules: ModEntry[] = []
for (let i = 0; i < nModules; i++) {
  const base = modOff + i * STRIDE
  const nameOff = mgBuf.readUInt32LE(base + 0)
  const nameLen = mgBuf.readUInt32LE(base + 4)
  const contOff = mgBuf.readUInt32LE(base + 8)
  const contLen = mgBuf.readUInt32LE(base + 12)
  const smOff = mgBuf.readUInt32LE(base + 16)
  const smLen = mgBuf.readUInt32LE(base + 20)
  const bcOff = mgBuf.readUInt32LE(base + 24)
  const bcLen = mgBuf.readUInt32LE(base + 28)
  const encoding = mgBuf.readUInt8(base + 32)
  const loader = mgBuf.readUInt8(base + 33)
  const moduleFormat = mgBuf.readUInt8(base + 34)
  const padding = mgBuf.readUInt8(base + 35)
  const name = mgBuf.slice(nameOff, nameOff + nameLen).toString("utf8").replace(/\0$/, "")
  modules.push({ nameOff, nameLen, contOff, contLen, smOff, smLen, bcOff, bcLen, encoding, loader, moduleFormat, padding, name })
  console.log(`  [${i}] ${name} cont=(${contOff},${contLen})`)
}

// ---- Patch 1: Fix undici reference in ALL modules ----
// Host bun v1.3.2 bundler compiles `import "undici"` as a bare global reference `undici`.
// Android bun v1.2.13 doesn't expose globalThis.undici, but it does expose `Undici` (capital U,
// the moduleExports object). `__reExport` skips the "default" key anyway, so the result is identical.
// Same-byte-count replacement: no offset adjustments needed.
// NOTE: This pattern appears in BOTH index.js AND worker.js (separate entry points).
const UNDICI_SEARCH  = Buffer.from('__reExport(exports_Undici, undici)')
const UNDICI_REPLACE = Buffer.from('__reExport(exports_Undici, Undici)')
console.log(`\nPatch 1: Replacing undici->Undici in ALL modules (same size, no offset changes)`)

let undiciPatchCount = 0
for (let i = 0; i < nModules; i++) {
  const mod = modules[i]
  const modSlice = mgBuf.slice(mod.contOff, mod.contOff + mod.contLen)
  let searchPos = 0
  while (true) {
    const pos = modSlice.indexOf(UNDICI_SEARCH, searchPos)
    if (pos < 0) break
    console.log(`  Found in [${i}] ${mod.name} at content offset ${pos}, replacing...`)
    UNDICI_REPLACE.copy(mgBuf, mod.contOff + pos)
    undiciPatchCount++
    searchPos = pos + UNDICI_SEARCH.length
  }
}
if (undiciPatchCount === 0) {
  console.error("WARNING: __reExport(exports_Undici, undici) not found in any module — skipping Patch 1")
} else {
  console.log(`  Patched ${undiciPatchCount} occurrence(s) across all modules`)
}

// No size change — module list and offsets are identical (no adjustment needed)
const patchedModList = Buffer.alloc(modLen)
for (let i = 0; i < nModules; i++) {
  const m = modules[i]
  const base = i * STRIDE
  patchedModList.writeUInt32LE(m.nameOff, base + 0)
  patchedModList.writeUInt32LE(m.nameLen, base + 4)
  patchedModList.writeUInt32LE(m.contOff, base + 8)
  patchedModList.writeUInt32LE(m.contLen, base + 12)
  patchedModList.writeUInt32LE(m.smOff, base + 16)
  patchedModList.writeUInt32LE(m.smLen, base + 20)
  patchedModList.writeUInt32LE(m.bcOff, base + 24)
  patchedModList.writeUInt32LE(m.bcLen, base + 28)
  patchedModList.writeUInt8(m.encoding, base + 32)
  patchedModList.writeUInt8(m.loader, base + 33)
  patchedModList.writeUInt8(m.moduleFormat, base + 34)
  patchedModList.writeUInt8(m.padding, base + 35)
}

// ---- Patch 2: Replace x86_64 librust_pty with ARM64 version ----
const libPtyModule = modules.find(m => m.name.includes("librust_pty") && !m.name.includes("arm64"))
// ARM64 librust_pty is optional — if present, it replaces the x86_64 version in the module graph
const ARM64_LIBRUST_PTY = process.env.ARM64_LIBRUST_PTY || path.join(OPENCODE_DIR, "../../node_modules/.bun/bun-pty@0.4.8/node_modules/bun-pty/rust-pty/target/release/librust_pty_arm64.so")
let arm64PtyBytes: Buffer | null = null
if (libPtyModule && fs.existsSync(ARM64_LIBRUST_PTY)) {
  arm64PtyBytes = Buffer.from(await Bun.file(ARM64_LIBRUST_PTY).arrayBuffer())
  console.log(`\nPatch 2: Replacing ${libPtyModule.name} (x86_64, ${libPtyModule.contLen} bytes) with ARM64 version (${arm64PtyBytes.length} bytes)`)
} else if (!libPtyModule) {
  console.log("\nPatch 2: No x86_64 librust_pty found in module graph, skipping")
} else {
  console.log("\nPatch 2: ARM64 librust_pty not found at expected path, skipping")
}

// Build the new module graph.
// Patch 1 (undici) was an in-place same-size edit — mgBuf already contains the fix.
// Patch 2 (librust_pty) replaces a variable-size region — requires offset adjustments.
let strDataParts: Buffer[]
if (arm64PtyBytes && libPtyModule) {
  // The original string data region [0, modOff) contains:
  //   [0, libPtyContOff)   = string data before PTY
  //   [libPtyContOff, libPtyEnd) = original PTY SO (replaced)
  //   [libPtyEnd, modOff) = string data after PTY
  //
  // Patch 2: replace pty SO in place (size may change → ptySizeDelta).
  // All StringPointer offsets >= libPtyContEnd shift by ptySizeDelta.
  // Patch 1 (undici) was a same-size in-place edit → no offset adjustments from it.

  const libPtyContOff = libPtyModule.contOff
  const libPtyContEnd = libPtyContOff + libPtyModule.contLen
  const ptySizeDelta = arm64PtyBytes.length - libPtyModule.contLen
  console.log(`  PTY size delta: ${ptySizeDelta} bytes`)

  strDataParts = [
    mgBuf.slice(0, libPtyContOff),
    arm64PtyBytes,
    mgBuf.slice(libPtyContEnd, modOff),
  ]

  // Fix up module list for PTY size change
  const patchedModList2 = Buffer.alloc(modLen)
  for (let i = 0; i < nModules; i++) {
    const m = modules[i]
    const base = i * STRIDE

    // Any offset >= libPtyContEnd shifts by ptySizeDelta
    const adjPty = (off: number) => off >= libPtyContEnd ? off + ptySizeDelta : off

    patchedModList2.writeUInt32LE(adjPty(m.nameOff), base + 0)
    patchedModList2.writeUInt32LE(m.nameLen, base + 4)
    patchedModList2.writeUInt32LE(adjPty(m.contOff), base + 8)
    // For libPtyModule: update contLen to new size
    patchedModList2.writeUInt32LE(m === libPtyModule ? arm64PtyBytes!.length : m.contLen, base + 12)
    patchedModList2.writeUInt32LE(adjPty(m.smOff), base + 16)
    patchedModList2.writeUInt32LE(m.smLen, base + 20)
    patchedModList2.writeUInt32LE(adjPty(m.bcOff), base + 24)
    patchedModList2.writeUInt32LE(m.bcLen, base + 28)
    patchedModList2.writeUInt8(m.encoding, base + 32)
    patchedModList2.writeUInt8(m.loader, base + 33)
    patchedModList2.writeUInt8(m.moduleFormat, base + 34)
    patchedModList2.writeUInt8(m.padding, base + 35)
  }

  const newStrDataSize = strDataParts.reduce((s, b) => s + b.length, 0)
  const newModOff = newStrDataSize

  const adjustArgvOff = (off: number) => off >= libPtyContEnd ? off + ptySizeDelta : off
  const newOffsetsByteCount = newModOff + patchedModList2.length

  const newOffsets = Buffer.alloc(OFFSETS_SIZE)
  newOffsets.writeBigUInt64LE(BigInt(newOffsetsByteCount), 0)
  newOffsets.writeUInt32LE(newModOff, 8)
  newOffsets.writeUInt32LE(modLen, 12)
  newOffsets.writeUInt32LE(entryId, 16)
  newOffsets.writeUInt32LE(adjustArgvOff(argvOff), 20)
  newOffsets.writeUInt32LE(argvLen, 24)
  newOffsets.writeUInt32LE(flags, 28)

  const patchedMg = Buffer.concat([...strDataParts, patchedModList2, newOffsets, trailerBuf])
  console.log(`Original module graph: ${moduleGraphBytes.length} bytes`)
  console.log(`Patched module graph:  ${patchedMg.length} bytes`)

  var finalModuleGraph = patchedMg
} else {
  // No PTY patch — undici was already patched in-place; module graph size unchanged.
  // Rebuild from mgBuf (which has the in-place undici edit) with original offsets.
  const strDataOnly = mgBuf.slice(0, modOff)
  const newOffsetsByteCount = modOff + patchedModList.length

  const newOffsets = Buffer.alloc(OFFSETS_SIZE)
  newOffsets.writeBigUInt64LE(BigInt(newOffsetsByteCount), 0)
  newOffsets.writeUInt32LE(modOff, 8)
  newOffsets.writeUInt32LE(modLen, 12)
  newOffsets.writeUInt32LE(entryId, 16)
  newOffsets.writeUInt32LE(argvOff, 20)
  newOffsets.writeUInt32LE(argvLen, 24)
  newOffsets.writeUInt32LE(flags, 28)

  const patchedMg = Buffer.concat([strDataOnly, patchedModList, newOffsets, trailerBuf])
  console.log(`Original module graph: ${moduleGraphBytes.length} bytes`)
  console.log(`Patched module graph:  ${patchedMg.length} bytes`)

  var finalModuleGraph = patchedMg
}

// Step 6: Create Android standalone binary
console.log("\n=== Step 6: Creating Android standalone binary ===")

const androidBunBytes = new Uint8Array(await Bun.file(ANDROID_BUN).arrayBuffer())
const androidBunSize = androidBunBytes.length
console.log(`Android bun size: ${androidBunSize}`)

// New total_byte_count = android_bun_size + module_graph.length + 8
const newTotalByteCount = androidBunSize + finalModuleGraph.length + 8

// Create the output buffer
const outputSize = androidBunSize + finalModuleGraph.length + 8
const output = new Uint8Array(outputSize)

// Copy Android bun binary
output.set(androidBunBytes, 0)

// Copy patched module graph
output.set(new Uint8Array(finalModuleGraph.buffer, finalModuleGraph.byteOffset, finalModuleGraph.length), androidBunSize)

// Write new total_byte_count as u64 LE
const totalView = new DataView(output.buffer, outputSize - 8, 8)
totalView.setUint32(0, newTotalByteCount & 0xFFFFFFFF, true)
totalView.setUint32(4, Math.floor(newTotalByteCount / 0x100000000), true)

const androidOutputPath = path.join(OUTPUT_DIR, "opencode")
await Bun.write(androidOutputPath, output)
fs.chmodSync(androidOutputPath, 0o755)

console.log(`\nAndroid standalone binary: ${androidOutputPath}`)
console.log(`Size: ${(outputSize / 1024 / 1024).toFixed(1)} MB`)

// Verify
const verifyBytes = new Uint8Array(await Bun.file(androidOutputPath).arrayBuffer())
const verifyView = new DataView(verifyBytes.buffer, verifyBytes.length - 8, 8)
const verifyTotal = verifyView.getUint32(0, true) + verifyView.getUint32(4, true) * 0x100000000
console.log(`Verification: total_byte_count=${verifyTotal}, file_size=${verifyBytes.length}, match=${verifyTotal === verifyBytes.length}`)

// Check ELF header
const elfMagic = String.fromCharCode(verifyBytes[0], verifyBytes[1], verifyBytes[2], verifyBytes[3])
console.log(`ELF magic: ${elfMagic === "\x7fELF" ? "OK" : "INVALID"}`)

console.log("\n=== Build complete! ===")
console.log(`Output: ${androidOutputPath}`)
