#!/usr/bin/env bun
/**
 * Build OpenCode for Android (aarch64)
 *
 * This script:
 * 1. Generates the models-snapshot.js
 * 2. Loads migrations
 * 3. Bundles OpenCode using Bun.build() with compile targeting the host platform
 * 4. Extracts the module graph from the compiled binary
 * 5. Appends it to our Android bun binary to create the final standalone
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"

// These are set by the build-opencode.sh wrapper script
const OPENCODE_DIR = process.env.OPENCODE_DIR || (() => { throw new Error("OPENCODE_DIR env var not set") })()
const ANDROID_BUN = process.env.ANDROID_BUN || (() => { throw new Error("ANDROID_BUN env var not set") })()
const OUTPUT_DIR = process.env.OUTPUT_DIR || (() => { throw new Error("OUTPUT_DIR env var not set") })()

// Validate Android bun exists
if (!fs.existsSync(ANDROID_BUN)) {
  console.error("Android bun binary not found at:", ANDROID_BUN)
  process.exit(1)
}

process.chdir(OPENCODE_DIR)

const VERSION = process.env.OPENCODE_VERSION || "1.3.13"
const CHANNEL = process.env.OPENCODE_CHANNEL || "latest"

console.log(`Building OpenCode v${VERSION} (channel: ${CHANNEL}) for Android aarch64`)

// Step 1: Generate models-snapshot.js
console.log("\n=== Step 1: Generating models-snapshot.js ===")
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
let modelsData: string = ""
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else {
  console.log(`Fetching from ${modelsUrl}/api.json ...`)
  let fetchErr: Error | null = null
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const resp = await fetch(`${modelsUrl}/api.json`, { signal: AbortSignal.timeout(15000) })
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
      modelsData = await resp.text()
      fetchErr = null
      break
    } catch (err: any) {
      fetchErr = err
      console.error(`  Attempt ${attempt}/3 failed: ${err.message}`)
      if (attempt < 3) await new Promise(r => setTimeout(r, 2000 * attempt))
    }
  }
  if (fetchErr) {
    console.error(`ERROR: Failed to fetch models after 3 attempts: ${fetchErr.message}`)
    process.exit(1)
  }
}
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// Step 2: Load migrations
console.log("\n=== Step 2: Loading migrations ===")
const migrationDirs = (
  await fs.promises.readdir(path.join(OPENCODE_DIR, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(OPENCODE_DIR, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// Step 3: Build with Bun.build() --compile for the HOST platform
// This creates a standalone binary for the host, from which we extract the module graph
console.log("\n=== Step 3: Bundling OpenCode ===")

const plugin = createSolidTransformPlugin()

// Find parser.worker.js
const localPath = path.resolve(OPENCODE_DIR, "node_modules/@opentui/core/parser.worker.js")
const rootPath = path.resolve(OPENCODE_DIR, "../../node_modules/@opentui/core/parser.worker.js")
let parserWorkerResolved: string
try {
  parserWorkerResolved = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
} catch {
  // Try bun's module resolution
  parserWorkerResolved = require.resolve("@opentui/core/parser.worker.js")
}
console.log(`Parser worker: ${parserWorkerResolved}`)

const workerPath = "./src/cli/cmd/tui/worker.ts"

const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(OPENCODE_DIR, parserWorkerResolved).replaceAll("\\", "/")

await $`rm -rf ${OUTPUT_DIR}`
await $`mkdir -p ${OUTPUT_DIR}`

// Build with --compile for the HOST platform to get a standalone binary
// We'll extract the module graph from it
const hostBinaryPath = path.join(OUTPUT_DIR, "opencode-host")

console.log("Building standalone binary for host platform...")
const result = await Bun.build({
  conditions: ["browser"],
  tsconfig: "./tsconfig.json",
  plugins: [plugin],
  compile: {
    autoloadBunfig: false,
    autoloadDotenv: false,
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    outfile: hostBinaryPath,
    execArgv: [`--user-agent=opencode/${VERSION}`, "--use-system-ca", "--"],
  },
  entrypoints: ["./src/index.ts", parserWorkerResolved, workerPath],
  define: {
    OPENCODE_VERSION: `'${VERSION}'`,
    OPENCODE_MIGRATIONS: JSON.stringify(migrations),
    OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
    OPENCODE_WORKER_PATH: workerPath,
    OPENCODE_CHANNEL: `'${CHANNEL}'`,
    OPENCODE_LIBC: "",
  },
})

if (!result.success) {
  console.error("Build failed:")
  for (const msg of result.logs) {
    console.error(msg)
  }
  process.exit(1)
}

console.log(`Host standalone binary: ${hostBinaryPath}`)

// Step 4: Extract module graph from host binary
console.log("\n=== Step 4: Extracting module graph ===")

const hostBinary = await Bun.file(hostBinaryPath).arrayBuffer()
const hostBytes = new Uint8Array(hostBinary)

// Standalone binary format (ELF):
//   [bun binary (seek_pos bytes)]
//   [module_graph bytes]
//   [total_byte_count as u64 LE (8 bytes)]
//
// Module graph internal layout:
//   [string data] [module list] [offsets (32 bytes)] [trailer "\n---- Bun! ----\n" (16 bytes)]
//
// offsets.byte_count = len(string_data) + len(module_list)
// total_byte_count = seek_pos + len(module_graph) + 8 = file_size
//
// We derive the module graph size from the trailer and offsets struct,
// WITHOUT relying on process.execPath (which may differ from the bun
// binary that was embedded during --compile).

const TRAILER_STR = "\n---- Bun! ----\n"
const TRAILER_LEN = TRAILER_STR.length  // 16
const OFFSETS_SIZE_CONST = 32

// Find trailer: it's near the end of the file, just before the final 8-byte u64.
// Search backwards from (end - 8) for the trailer sentinel.
const trailerBuf = Buffer.from(TRAILER_STR)
const searchBuf = Buffer.from(hostBytes.buffer, hostBytes.byteOffset, hostBytes.length)
const trailerEnd = hostBytes.length - 8  // trailer must end here
const expectedTrailerStart = trailerEnd - TRAILER_LEN

// Verify trailer at expected position
const foundTrailer = searchBuf.compare(
  trailerBuf, 0, TRAILER_LEN,
  expectedTrailerStart, trailerEnd
) === 0

if (!foundTrailer) {
  console.error("ERROR: Bun standalone trailer not found at expected position")
  console.error("       The standalone binary format may have changed.")
  process.exit(1)
}

// Read offsets struct (32 bytes) just before the trailer
const offsetsStart = expectedTrailerStart - OFFSETS_SIZE_CONST
const offsetsByteCount = Number(searchBuf.readBigUInt64LE(offsetsStart))

// Module graph total size = byte_count (string data + module list) + offsets(32) + trailer(16)
const moduleGraphSize = offsetsByteCount + OFFSETS_SIZE_CONST + TRAILER_LEN
const hostBunSize = hostBytes.length - 8 - moduleGraphSize

console.log(`Host standalone size: ${hostBytes.length}`)
console.log(`Derived host bun size: ${hostBunSize}`)
console.log(`Module graph size: ${moduleGraphSize}`)

if (hostBunSize <= 0) {
  console.error(`ERROR: Derived host bun size is ${hostBunSize} — something is wrong`)
  process.exit(1)
}

const moduleGraphBytes = hostBytes.slice(hostBunSize, hostBytes.length - 8)
console.log(`Module graph extracted: ${moduleGraphBytes.length} bytes`)
console.log(`Trailer verified: OK`)

// Step 5: Patch the module graph for Android
console.log("\n=== Step 5: Patching module graph for Android ===")

// The module graph format (from StandaloneModuleGraph.zig):
//   [string data: all file names, contents, sourcemaps, bytecodes concatenated]
//   [CompiledModuleGraphFile array: stride=36 bytes each]
//   [Offsets struct: 32 bytes]
//   [trailer: "\n---- Bun! ----\n"]
//
// Offsets struct layout (32 bytes, little-endian):
//   byte_count:              u64  (8 bytes) - size of everything before the Offsets struct
//   modules_ptr.offset:      u32  (4 bytes)
//   modules_ptr.length:      u32  (4 bytes)
//   entry_point_id:          u32  (4 bytes)
//   compile_exec_argv.offset:u32  (4 bytes)
//   compile_exec_argv.length:u32  (4 bytes)
//   flags:                   u32  (4 bytes)
//
// CompiledModuleGraphFile layout (36 bytes):
//   name.offset:     u32 (4)
//   name.length:     u32 (4)
//   contents.offset: u32 (4)
//   contents.length: u32 (4)
//   sourcemap.offset:u32 (4)
//   sourcemap.length:u32 (4)
//   bytecode.offset: u32 (4)
//   bytecode.length: u32 (4)
//   encoding:        u8  (1)
//   loader:          u8  (1)
//   module_format:   u8  (1)
//   padding:         u8  (1)

const mgTrailer = "\n---- Bun! ----\n"
const mgTrailerBuf = Buffer.from(mgTrailer)
const OFFSETS_SIZE = 32
const STRIDE = 36

// Parse the module graph
const mgBuf = Buffer.from(moduleGraphBytes)
const trailerPosInMg = mgBuf.lastIndexOf(mgTrailerBuf)
if (trailerPosInMg < 0) throw new Error("Trailer not found in module graph!")

// Offsets struct is just before the trailer
const mgOffsetsStart = trailerPosInMg - OFFSETS_SIZE
const byteCount = Number(mgBuf.readBigUInt64LE(mgOffsetsStart))  // points to start of Offsets struct
const modOff = mgBuf.readUInt32LE(mgOffsetsStart + 8)
const modLen = mgBuf.readUInt32LE(mgOffsetsStart + 12)
const entryId = mgBuf.readUInt32LE(mgOffsetsStart + 16)
const argvOff = mgBuf.readUInt32LE(mgOffsetsStart + 20)
const argvLen = mgBuf.readUInt32LE(mgOffsetsStart + 24)
const flags = mgBuf.readUInt32LE(mgOffsetsStart + 28)

console.log(`Module graph: trailer at ${trailerPosInMg}, offsets at ${mgOffsetsStart}`)
console.log(`byte_count=${byteCount}, modules_ptr=(${modOff},${modLen}), entry_id=${entryId}`)

const nModules = modLen / STRIDE
console.log(`Number of modules: ${nModules}`)

// Parse all module entries
interface ModEntry {
  nameOff: number; nameLen: number
  contOff: number; contLen: number
  smOff: number; smLen: number
  bcOff: number; bcLen: number
  encoding: number; loader: number; moduleFormat: number; padding: number
  name: string
}

const modules: ModEntry[] = []
for (let i = 0; i < nModules; i++) {
  const base = modOff + i * STRIDE
  const nameOff = mgBuf.readUInt32LE(base + 0)
  const nameLen = mgBuf.readUInt32LE(base + 4)
  const contOff = mgBuf.readUInt32LE(base + 8)
  const contLen = mgBuf.readUInt32LE(base + 12)
  const smOff = mgBuf.readUInt32LE(base + 16)
  const smLen = mgBuf.readUInt32LE(base + 20)
  const bcOff = mgBuf.readUInt32LE(base + 24)
  const bcLen = mgBuf.readUInt32LE(base + 28)
  const encoding = mgBuf.readUInt8(base + 32)
  const loader = mgBuf.readUInt8(base + 33)
  const moduleFormat = mgBuf.readUInt8(base + 34)
  const padding = mgBuf.readUInt8(base + 35)
  const name = mgBuf.slice(nameOff, nameOff + nameLen).toString("utf8").replace(/\0$/, "")
  modules.push({ nameOff, nameLen, contOff, contLen, smOff, smLen, bcOff, bcLen, encoding, loader, moduleFormat, padding, name })
  console.log(`  [${i}] ${name} cont=(${contOff},${contLen})`)
}

// ---- Patch 1: Fix undici reference in ALL modules ----
// Host bun v1.3.2 bundler compiles `import "undici"` as a bare global reference `undici`.
// Android bun v1.2.13 doesn't expose globalThis.undici, but it does expose `Undici` (capital U,
// the moduleExports object). `__reExport` skips the "default" key anyway, so the result is identical.
// Same-byte-count replacement: no offset adjustments needed.
// NOTE: This pattern appears in BOTH index.js AND worker.js (separate entry points).
const UNDICI_SEARCH  = Buffer.from('__reExport(exports_Undici, undici)')
const UNDICI_REPLACE = Buffer.from('__reExport(exports_Undici, Undici)')
console.log(`\nPatch 1: Replacing undici->Undici in ALL modules (same size, no offset changes)`)

let undiciPatchCount = 0
for (let i = 0; i < nModules; i++) {
  const mod = modules[i]
  const modSlice = mgBuf.slice(mod.contOff, mod.contOff + mod.contLen)
  let searchPos = 0
  while (true) {
    const pos = modSlice.indexOf(UNDICI_SEARCH, searchPos)
    if (pos < 0) break
    console.log(`  Found in [${i}] ${mod.name} at content offset ${pos}, replacing...`)
    UNDICI_REPLACE.copy(mgBuf, mod.contOff + pos)
    undiciPatchCount++
    searchPos = pos + UNDICI_SEARCH.length
  }
}
if (undiciPatchCount === 0) {
  console.error("WARNING: __reExport(exports_Undici, undici) not found in any module — skipping Patch 1")
} else {
  console.log(`  Patched ${undiciPatchCount} occurrence(s) across all modules`)
}

// No size change — module list and offsets are identical (no adjustment needed)
const patchedModList = Buffer.alloc(modLen)
for (let i = 0; i < nModules; i++) {
  const m = modules[i]
  const base = i * STRIDE
  patchedModList.writeUInt32LE(m.nameOff, base + 0)
  patchedModList.writeUInt32LE(m.nameLen, base + 4)
  patchedModList.writeUInt32LE(m.contOff, base + 8)
  patchedModList.writeUInt32LE(m.contLen, base + 12)
  patchedModList.writeUInt32LE(m.smOff, base + 16)
  patchedModList.writeUInt32LE(m.smLen, base + 20)
  patchedModList.writeUInt32LE(m.bcOff, base + 24)
  patchedModList.writeUInt32LE(m.bcLen, base + 28)
  patchedModList.writeUInt8(m.encoding, base + 32)
  patchedModList.writeUInt8(m.loader, base + 33)
  patchedModList.writeUInt8(m.moduleFormat, base + 34)
  patchedModList.writeUInt8(m.padding, base + 35)
}

// ---- Patch 2: Replace x86_64 librust_pty with ARM64 version ----
const libPtyModule = modules.find(m => m.name.includes("librust_pty") && !m.name.includes("arm64"))
// ARM64 librust_pty is optional — if present, it replaces the x86_64 version in the module graph
const ARM64_LIBRUST_PTY = process.env.ARM64_LIBRUST_PTY || path.join(OPENCODE_DIR, "../../node_modules/.bun/bun-pty@0.4.8/node_modules/bun-pty/rust-pty/target/release/librust_pty_arm64.so")
let arm64PtyBytes: Buffer | null = null
if (libPtyModule && fs.existsSync(ARM64_LIBRUST_PTY)) {
  arm64PtyBytes = Buffer.from(await Bun.file(ARM64_LIBRUST_PTY).arrayBuffer())
  console.log(`\nPatch 2: Replacing ${libPtyModule.name} (x86_64, ${libPtyModule.contLen} bytes) with ARM64 version (${arm64PtyBytes.length} bytes)`)
} else if (!libPtyModule) {
  console.log("\nPatch 2: No x86_64 librust_pty found in module graph, skipping")
} else {
  console.log("\nPatch 2: ARM64 librust_pty not found at expected path, skipping")
}

// Build the new module graph.
// Patch 1 (undici) was an in-place same-size edit — mgBuf already contains the fix.
// Patch 2 (librust_pty) replaces a variable-size region — requires offset adjustments.
let strDataParts: Buffer[]
if (arm64PtyBytes && libPtyModule) {
  // The original string data region [0, modOff) contains:
  //   [0, libPtyContOff)   = string data before PTY
  //   [libPtyContOff, libPtyEnd) = original PTY SO (replaced)
  //   [libPtyEnd, modOff) = string data after PTY
  //
  // Patch 2: replace pty SO in place (size may change → ptySizeDelta).
  // All StringPointer offsets >= libPtyContEnd shift by ptySizeDelta.
  // Patch 1 (undici) was a same-size in-place edit → no offset adjustments from it.

  const libPtyContOff = libPtyModule.contOff
  const libPtyContEnd = libPtyContOff + libPtyModule.contLen
  const ptySizeDelta = arm64PtyBytes.length - libPtyModule.contLen
  console.log(`  PTY size delta: ${ptySizeDelta} bytes`)

  strDataParts = [
    mgBuf.slice(0, libPtyContOff),
    arm64PtyBytes,
    mgBuf.slice(libPtyContEnd, modOff),
  ]

  // Fix up module list for PTY size change
  const patchedModList2 = Buffer.alloc(modLen)
  for (let i = 0; i < nModules; i++) {
    const m = modules[i]
    const base = i * STRIDE

    // Any offset >= libPtyContEnd shifts by ptySizeDelta
    const adjPty = (off: number) => off >= libPtyContEnd ? off + ptySizeDelta : off

    patchedModList2.writeUInt32LE(adjPty(m.nameOff), base + 0)
    patchedModList2.writeUInt32LE(m.nameLen, base + 4)
    patchedModList2.writeUInt32LE(adjPty(m.contOff), base + 8)
    // For libPtyModule: update contLen to new size
    patchedModList2.writeUInt32LE(m === libPtyModule ? arm64PtyBytes!.length : m.contLen, base + 12)
    patchedModList2.writeUInt32LE(adjPty(m.smOff), base + 16)
    patchedModList2.writeUInt32LE(m.smLen, base + 20)
    patchedModList2.writeUInt32LE(adjPty(m.bcOff), base + 24)
    patchedModList2.writeUInt32LE(m.bcLen, base + 28)
    patchedModList2.writeUInt8(m.encoding, base + 32)
    patchedModList2.writeUInt8(m.loader, base + 33)
    patchedModList2.writeUInt8(m.moduleFormat, base + 34)
    patchedModList2.writeUInt8(m.padding, base + 35)
  }

  const newStrDataSize = strDataParts.reduce((s, b) => s + b.length, 0)
  const newModOff = newStrDataSize

  const adjustArgvOff = (off: number) => off >= libPtyContEnd ? off + ptySizeDelta : off
  const newOffsetsByteCount = newModOff + patchedModList2.length

  const newOffsets = Buffer.alloc(OFFSETS_SIZE)
  newOffsets.writeBigUInt64LE(BigInt(newOffsetsByteCount), 0)
  newOffsets.writeUInt32LE(newModOff, 8)
  newOffsets.writeUInt32LE(modLen, 12)
  newOffsets.writeUInt32LE(entryId, 16)
  newOffsets.writeUInt32LE(adjustArgvOff(argvOff), 20)
  newOffsets.writeUInt32LE(argvLen, 24)
  newOffsets.writeUInt32LE(flags, 28)

  const patchedMg = Buffer.concat([...strDataParts, patchedModList2, newOffsets, mgTrailerBuf])
  console.log(`Original module graph: ${moduleGraphBytes.length} bytes`)
  console.log(`Patched module graph:  ${patchedMg.length} bytes`)

  var finalModuleGraph = patchedMg
} else {
  // No PTY patch — undici was already patched in-place; module graph size unchanged.
  // Rebuild from mgBuf (which has the in-place undici edit) with original offsets.
  const strDataOnly = mgBuf.slice(0, modOff)
  const newOffsetsByteCount = modOff + patchedModList.length

  const newOffsets = Buffer.alloc(OFFSETS_SIZE)
  newOffsets.writeBigUInt64LE(BigInt(newOffsetsByteCount), 0)
  newOffsets.writeUInt32LE(modOff, 8)
  newOffsets.writeUInt32LE(modLen, 12)
  newOffsets.writeUInt32LE(entryId, 16)
  newOffsets.writeUInt32LE(argvOff, 20)
  newOffsets.writeUInt32LE(argvLen, 24)
  newOffsets.writeUInt32LE(flags, 28)

  const patchedMg = Buffer.concat([strDataOnly, patchedModList, newOffsets, mgTrailerBuf])
  console.log(`Original module graph: ${moduleGraphBytes.length} bytes`)
  console.log(`Patched module graph:  ${patchedMg.length} bytes`)

  var finalModuleGraph = patchedMg
}

// Step 6: Create Android standalone binary
console.log("\n=== Step 6: Creating Android standalone binary ===")

const androidBunBytes = new Uint8Array(await Bun.file(ANDROID_BUN).arrayBuffer())
const androidBunSize = androidBunBytes.length
console.log(`Android bun size: ${androidBunSize}`)

// New total_byte_count = android_bun_size + module_graph.length + 8
const newTotalByteCount = androidBunSize + finalModuleGraph.length + 8

// Create the output buffer
const outputSize = androidBunSize + finalModuleGraph.length + 8
const output = new Uint8Array(outputSize)

// Copy Android bun binary
output.set(androidBunBytes, 0)

// Copy patched module graph
output.set(new Uint8Array(finalModuleGraph.buffer, finalModuleGraph.byteOffset, finalModuleGraph.length), androidBunSize)

// Write new total_byte_count as u64 LE
const totalView = new DataView(output.buffer, outputSize - 8, 8)
totalView.setUint32(0, newTotalByteCount & 0xFFFFFFFF, true)
totalView.setUint32(4, Math.floor(newTotalByteCount / 0x100000000), true)

const androidOutputPath = path.join(OUTPUT_DIR, "opencode")
await Bun.write(androidOutputPath, output)
fs.chmodSync(androidOutputPath, 0o755)

console.log(`\nAndroid standalone binary: ${androidOutputPath}`)
console.log(`Size: ${(outputSize / 1024 / 1024).toFixed(1)} MB`)

// Verify
const verifyBytes = new Uint8Array(await Bun.file(androidOutputPath).arrayBuffer())
const verifyView = new DataView(verifyBytes.buffer, verifyBytes.length - 8, 8)
const verifyTotal = verifyView.getUint32(0, true) + verifyView.getUint32(4, true) * 0x100000000
console.log(`Verification: total_byte_count=${verifyTotal}, file_size=${verifyBytes.length}, match=${verifyTotal === verifyBytes.length}`)

// Check ELF header
const elfMagic = String.fromCharCode(verifyBytes[0], verifyBytes[1], verifyBytes[2], verifyBytes[3])
console.log(`ELF magic: ${elfMagic === "\x7fELF" ? "OK" : "INVALID"}`)

console.log("\n=== Build complete! ===")
console.log(`Output: ${androidOutputPath}`)
